image: "dev.gitlab.org:5005/gitlab/gitlab-build-images:ruby-2.4.4-golang-1.9-git-2.18-chrome-67.0-node-8.x-yarn-1.2-postgresql-9.6-graphicsmagick-1.3.29"

.dedicated-runner: &dedicated-runner
  tags:
    - gitlab-org

.default-cache: &default-cache
  key: "ruby-2.4.4-debian-stretch-with-yarn"
  paths:
    - vendor/ruby
    - .yarn-cache/
    - vendor/gitaly-ruby

.pull-cache: &pull-cache
  cache:
    <<: *default-cache
    policy: pull

variables:
  MYSQL_ALLOW_EMPTY_PASSWORD: "1"
  RAILS_ENV: "test"
  NODE_ENV: "test"
  SIMPLECOV: "true"
  GIT_DEPTH: "20"
  GIT_SUBMODULE_STRATEGY: "none"
  GET_SOURCES_ATTEMPTS: "3"
  NO_KNAPSACK: "1"

stages:
  - build
  - prepare
  - test
  - post-test
  - pages
  - post-cleanup

before_script:
  - bundle --version
  - date
  - source scripts/utils.sh
  - date
  - source scripts/prepare_build.sh
  - date

after_script:
  - date

.use-pg: &use-pg
  services:
    # As of Jan 2018, we don't have a strong reason to upgrade to 9.6 for CI yet,
    # so using the least common denominator ensures backwards compatibility
    # (as many users are still using 9.2).
    - postgres:9.2
    - redis:alpine

.rails5-variables: &rails5-variables
  script:
    - export RAILS5=${RAILS5}
    - export BUNDLE_GEMFILE=${BUNDLE_GEMFILE}

setup-test-env:
  <<: *dedicated-runner
  <<: *use-pg
  stage: prepare
  cache:
    <<: *default-cache
  script:
    - bundle exec ruby -Ispec -e 'require "spec_helper" ; TestEnv.init'
    - scripts/gitaly-test-build # Do not use 'bundle exec' here
    - BUNDLE_GEMFILE=Gemfile.rails5 bundle install $BUNDLE_INSTALL_FLAGS
  artifacts:
    expire_in: 7d
    paths:
      - tmp/tests
      - config/secrets.yml
      - vendor/gitaly-ruby

rspec-mike:
  <<: *use-pg
  <<: *dedicated-runner
  <<: *pull-cache
  <<: *rails5-variables
  script:
    - JOB_NAME=( $CI_JOB_NAME )
    - export CACHE_CLASSES=true
    - scripts/gitaly-test-spawn
    - bundle exec rspec spec/tasks/gitlab/cleanup_rake_spec.rb:161
  artifacts:
    expire_in: 31d
    when: always
    paths:
      - tmp/capybara/
