image: "ruby:2.1"

services:
  - mysql:latest
  - redis:alpine

cache:
  key: "ruby21"
  paths:
  - vendor/apt
  - vendor/ruby

variables:
  MYSQL_ALLOW_EMPTY_PASSWORD: "1"
  # retry tests only in CI environment
  RSPEC_RETRY_RETRY_COUNT: "3"
  RAILS_ENV: "test"
  SIMPLECOV: "true"
  USE_DB: "true"
  USE_BUNDLE_INSTALL: "true"
  GIT_DEPTH: "5"

before_script:
  - source ./scripts/prepare_build.sh
  - cp config/gitlab.yml.example config/gitlab.yml
  - bundle --version
  - '[ "$USE_BUNDLE_INSTALL" != "true" ] || retry bundle install --without postgres production --jobs $(nproc) "${FLAGS[@]}"'
  - retry gem install knapsack
  - '[ "$USE_DB" != "true" ] || bundle exec rake db:drop db:create db:schema:load db:migrate'

stages:
- prepare
- test
- post-test

# Prepare and merge knapsack tests

.knapsack-state: &knapsack-state
  services: []
  variables:
    USE_DB: "false"
    USE_BUNDLE_INSTALL: "false"
  cache:
    key: "knapsack"
    paths:
    - knapsack/
  artifacts:
    paths:
    - knapsack/

knapsack:
  <<: *knapsack-state
  stage: prepare
  script:
    - mkdir -p knapsack/
    - '[[ -f knapsack/rspec_report.json ]] || echo "{}" > knapsack/rspec_report.json'
    - '[[ -f knapsack/spinach_report.json ]] || echo "{}" > knapsack/spinach_report.json'

update-knapsack:
  <<: *knapsack-state
  stage: post-test
  script:
    - scripts/merge-reports knapsack/rspec_report.json knapsack/rspec_node_*.json
    - scripts/merge-reports knapsack/spinach_report.json knapsack/spinach_node_*.json
    - rm -f knapsack/*_node_*.json
  only:
    - master

# Execute all testing suites

.rspec-knapsack: &rspec-knapsack
  stage: test
  script:
    - bundle exec rake assets:precompile 2>/dev/null
    - JOB_NAME=( $CI_BUILD_NAME )
    - export CI_NODE_INDEX=${JOB_NAME[1]}
    - export CI_NODE_TOTAL=${JOB_NAME[2]}
    - export KNAPSACK_REPORT_PATH=knapsack/rspec_node_${CI_NODE_INDEX}_${CI_NODE_TOTAL}_report.json
    - export KNAPSACK_GENERATE_REPORT=true
    - cp knapsack/rspec_report.json ${KNAPSACK_REPORT_PATH}
    - knapsack rspec
  artifacts:
    paths:
    - knapsack/

.spinach-knapsack: &spinach-knapsack
  stage: test
  script:
    - bundle exec rake assets:precompile 2>/dev/null
    - JOB_NAME=( $CI_BUILD_NAME )
    - export CI_NODE_INDEX=${JOB_NAME[1]}
    - export CI_NODE_TOTAL=${JOB_NAME[2]}
    - export KNAPSACK_REPORT_PATH=knapsack/spinach_node_${CI_NODE_INDEX}_${CI_NODE_TOTAL}_report.json
    - export KNAPSACK_GENERATE_REPORT=true
    - cp knapsack/spinach_report.json ${KNAPSACK_REPORT_PATH}
    - knapsack spinach "-r rerun" || retry '[ ! -e tmp/spinach-rerun.txt ] || bundle exec spinach -r rerun $(cat tmp/spinach-rerun.txt)'
  artifacts:
    paths:
    - knapsack/

rspec 0 60: *rspec-knapsack
rspec 1 60: *rspec-knapsack
rspec 2 60: *rspec-knapsack
rspec 3 60: *rspec-knapsack
rspec 4 60: *rspec-knapsack
rspec 5 60: *rspec-knapsack
rspec 6 60: *rspec-knapsack
rspec 7 60: *rspec-knapsack
rspec 8 60: *rspec-knapsack
rspec 9 60: *rspec-knapsack
rspec 10 60: *rspec-knapsack
rspec 11 60: *rspec-knapsack
rspec 12 60: *rspec-knapsack
rspec 13 60: *rspec-knapsack
rspec 14 60: *rspec-knapsack
rspec 15 60: *rspec-knapsack
rspec 16 60: *rspec-knapsack
rspec 17 60: *rspec-knapsack
rspec 18 60: *rspec-knapsack
rspec 19 60: *rspec-knapsack
rspec 20 60: *rspec-knapsack
rspec 21 60: *rspec-knapsack
rspec 22 60: *rspec-knapsack
rspec 23 60: *rspec-knapsack
rspec 24 60: *rspec-knapsack
rspec 25 60: *rspec-knapsack
rspec 26 60: *rspec-knapsack
rspec 27 60: *rspec-knapsack
rspec 28 60: *rspec-knapsack
rspec 29 60: *rspec-knapsack
rspec 30 60: *rspec-knapsack
rspec 31 60: *rspec-knapsack
rspec 32 60: *rspec-knapsack
rspec 33 60: *rspec-knapsack
rspec 34 60: *rspec-knapsack
rspec 35 60: *rspec-knapsack
rspec 36 60: *rspec-knapsack
rspec 37 60: *rspec-knapsack
rspec 38 60: *rspec-knapsack
rspec 39 60: *rspec-knapsack
rspec 40 60: *rspec-knapsack
rspec 41 60: *rspec-knapsack
rspec 42 60: *rspec-knapsack
rspec 43 60: *rspec-knapsack
rspec 44 60: *rspec-knapsack
rspec 45 60: *rspec-knapsack
rspec 46 60: *rspec-knapsack
rspec 47 60: *rspec-knapsack
rspec 48 60: *rspec-knapsack
rspec 49 60: *rspec-knapsack
rspec 50 60: *rspec-knapsack
rspec 51 60: *rspec-knapsack
rspec 52 60: *rspec-knapsack
rspec 53 60: *rspec-knapsack
rspec 54 60: *rspec-knapsack
rspec 55 60: *rspec-knapsack
rspec 56 60: *rspec-knapsack
rspec 57 60: *rspec-knapsack
rspec 58 60: *rspec-knapsack
rspec 59 60: *rspec-knapsack

spinach 0 60: *spinach-knapsack
spinach 1 60: *spinach-knapsack
spinach 2 60: *spinach-knapsack
spinach 3 60: *spinach-knapsack
spinach 4 60: *spinach-knapsack
spinach 5 60: *spinach-knapsack
spinach 6 60: *spinach-knapsack
spinach 7 60: *spinach-knapsack
spinach 8 60: *spinach-knapsack
spinach 9 60: *spinach-knapsack
spinach 10 60: *spinach-knapsack
spinach 11 60: *spinach-knapsack
spinach 12 60: *spinach-knapsack
spinach 13 60: *spinach-knapsack
spinach 14 60: *spinach-knapsack
spinach 15 60: *spinach-knapsack
spinach 16 60: *spinach-knapsack
spinach 17 60: *spinach-knapsack
spinach 18 60: *spinach-knapsack
spinach 19 60: *spinach-knapsack
spinach 20 60: *spinach-knapsack
spinach 21 60: *spinach-knapsack
spinach 22 60: *spinach-knapsack
spinach 23 60: *spinach-knapsack
spinach 24 60: *spinach-knapsack
spinach 25 60: *spinach-knapsack
spinach 26 60: *spinach-knapsack
spinach 27 60: *spinach-knapsack
spinach 28 60: *spinach-knapsack
spinach 29 60: *spinach-knapsack
spinach 30 60: *spinach-knapsack
spinach 31 60: *spinach-knapsack
spinach 32 60: *spinach-knapsack
spinach 33 60: *spinach-knapsack
spinach 34 60: *spinach-knapsack
spinach 35 60: *spinach-knapsack
spinach 36 60: *spinach-knapsack
spinach 37 60: *spinach-knapsack
spinach 38 60: *spinach-knapsack
spinach 39 60: *spinach-knapsack
spinach 40 60: *spinach-knapsack
spinach 41 60: *spinach-knapsack
spinach 42 60: *spinach-knapsack
spinach 43 60: *spinach-knapsack
spinach 44 60: *spinach-knapsack
spinach 45 60: *spinach-knapsack
spinach 46 60: *spinach-knapsack
spinach 47 60: *spinach-knapsack
spinach 48 60: *spinach-knapsack
spinach 49 60: *spinach-knapsack
spinach 50 60: *spinach-knapsack
spinach 51 60: *spinach-knapsack
spinach 52 60: *spinach-knapsack
spinach 53 60: *spinach-knapsack
spinach 54 60: *spinach-knapsack
spinach 55 60: *spinach-knapsack
spinach 56 60: *spinach-knapsack
spinach 57 60: *spinach-knapsack
spinach 58 60: *spinach-knapsack
spinach 59 60: *spinach-knapsack

# Execute all testing suites against Ruby 2.2

.ruby-22: &ruby-22
  image: "ruby:2.2"
  only:
    - master
  cache:
    key: "ruby22"
    paths:
    - vendor

.rspec-knapsack-ruby22: &rspec-knapsack-ruby22
  <<: *rspec-knapsack
  <<: *ruby-22

.spinach-knapsack-ruby22: &spinach-knapsack-ruby22
  <<: *spinach-knapsack
  <<: *ruby-22
  
rspec 0 20 ruby22: *rspec-knapsack-ruby22
rspec 1 20 ruby22: *rspec-knapsack-ruby22
rspec 2 20 ruby22: *rspec-knapsack-ruby22
rspec 3 20 ruby22: *rspec-knapsack-ruby22
rspec 4 20 ruby22: *rspec-knapsack-ruby22
rspec 5 20 ruby22: *rspec-knapsack-ruby22
rspec 6 20 ruby22: *rspec-knapsack-ruby22
rspec 7 20 ruby22: *rspec-knapsack-ruby22
rspec 8 20 ruby22: *rspec-knapsack-ruby22
rspec 9 20 ruby22: *rspec-knapsack-ruby22
rspec 10 20 ruby22: *rspec-knapsack-ruby22
rspec 11 20 ruby22: *rspec-knapsack-ruby22
rspec 12 20 ruby22: *rspec-knapsack-ruby22
rspec 13 20 ruby22: *rspec-knapsack-ruby22
rspec 14 20 ruby22: *rspec-knapsack-ruby22
rspec 15 20 ruby22: *rspec-knapsack-ruby22
rspec 16 20 ruby22: *rspec-knapsack-ruby22
rspec 17 20 ruby22: *rspec-knapsack-ruby22
rspec 18 20 ruby22: *rspec-knapsack-ruby22
rspec 19 20 ruby22: *rspec-knapsack-ruby22

spinach 0 10 ruby22: *spinach-knapsack-ruby22
spinach 1 10 ruby22: *spinach-knapsack-ruby22
spinach 2 10 ruby22: *spinach-knapsack-ruby22
spinach 3 10 ruby22: *spinach-knapsack-ruby22
spinach 4 10 ruby22: *spinach-knapsack-ruby22
spinach 5 10 ruby22: *spinach-knapsack-ruby22
spinach 6 10 ruby22: *spinach-knapsack-ruby22
spinach 7 10 ruby22: *spinach-knapsack-ruby22
spinach 8 10 ruby22: *spinach-knapsack-ruby22
spinach 9 10 ruby22: *spinach-knapsack-ruby22

# Other generic tests

.exec: &exec
  stage: test
  script:
    - bundle exec $CI_BUILD_NAME

teaspoon: *exec
rubocop: *exec
rake scss_lint: *exec
rake brakeman: *exec
rake flog: *exec
rake flay: *exec
rake db:migrate:reset: *exec
license_finder: *exec

bundler:audit:
  stage: test
  only:
    - master
  script:
    - "bundle exec bundle-audit check --update --ignore OSVDB-115941"

# Notify slack in the end

notify:slack:
  stage: post-test
  script:
    - ./scripts/notify_slack.sh "#builds" "Build on \`$CI_BUILD_REF_NAME\` failed! Commit \`$(git log -1 --oneline)\` See <https://gitlab.com/gitlab-org/$(basename "$PWD")/commit/"$CI_BUILD_REF"/builds>"
  when: on_failure
  only:
    - master@gitlab-org/gitlab-ce
    - tags@gitlab-org/gitlab-ce
    - master@gitlab-org/gitlab-ee
    - tags@gitlab-org/gitlab-ee
