image: "dev.gitlab.org:5005/gitlab/gitlab-build-images:ruby-2.3.6-golang-1.9-git-2.14-chrome-63.0-node-8.x-yarn-1.2-postgresql-9.6"

.dedicated-runner: &dedicated-runner
  retry: 1
  tags:
    - gitlab-org

.default-cache: &default-cache
  key: "ruby-2.3.6-with-yarn"
  paths:
    - vendor/ruby
    - .yarn-cache/

.push-cache: &push-cache
  cache:
    <<: *default-cache
    policy: push

.pull-cache: &pull-cache
  cache:
    <<: *default-cache
    policy: pull

variables:
  MYSQL_ALLOW_EMPTY_PASSWORD: "1"
  RAILS_ENV: "test"
  NODE_ENV: "test"
  SIMPLECOV: "true"
  GIT_DEPTH: "20"
  GIT_SUBMODULE_STRATEGY: "none"
  GET_SOURCES_ATTEMPTS: "3"
  KNAPSACK_RSPEC_SUITE_REPORT_PATH: knapsack/${CI_PROJECT_NAME}/rspec_report-master.json
  KNAPSACK_SPINACH_SUITE_REPORT_PATH: knapsack/${CI_PROJECT_NAME}/spinach_report-master.json
  FLAKY_RSPEC_SUITE_REPORT_PATH: rspec_flaky/report-suite.json

before_script:
  - bundle --version
  - source scripts/utils.sh
  - source scripts/prepare_build.sh

stages:
  - build
  - prepare
  - test



# Predefined scopes
.tests-metadata-state: &tests-metadata-state
  <<: *dedicated-runner
  variables:
    TESTS_METADATA_S3_BUCKET: "gitlab-ce-cache"
  before_script:
    - source scripts/utils.sh
  artifacts:
    expire_in: 31d
    paths:
      - knapsack/
      - rspec_flaky/

.use-pg: &use-pg
  services:
    # As of Jan 2018, we don't have a strong reason to upgrade to 9.6 for CI yet,
    # so using the least common denominator ensures backwards compatibility
    # (as many users are still using 9.2).
    - postgres:9.2
    - redis:alpine

.use-mysql: &use-mysql
  services:
    - mysql:latest
    - redis:alpine

# Skip all jobs except the ones that begin with 'docs/'.
# Used for commits including ONLY documentation changes.
# https://docs.gitlab.com/ce/development/writing_documentation.html#testing
.except-docs: &except-docs
  except:
    - /(^docs[\/-].*|.*-docs$)/

.except-qa: &except-qa
  except:
    - /(^qa[\/-].*|.*-qa$)/

.except-docs-and-qa: &except-docs-and-qa
  except:
    - /(^docs[\/-].*|.*-docs$)/
    - /(^qa[\/-].*|.*-qa$)/

rspec-mike:
  <<: *dedicated-runner
  <<: *except-docs-and-qa
  <<: *pull-cache
  <<: *use-pg
  stage: test
  script:
    - export CACHE_CLASSES=true
    - scripts/gitaly-test-spawn
    - rspec --color --format documentation spec/requests/api/users_spec.rb spec/factories_spec.rb spec/models/cycle_analytics/issue_spec.rb spec/features/issues/gfm_autocomplete_spec.rb spec/services/system_note_service_spec.rb spec/features/merge_request/user_selects_branches_for_new_mr_spec.rb spec/helpers/markup_helper_spec.rb spec/requests/api/v3/triggers_spec.rb spec/services/create_deployment_service_spec.rb spec/features/explore/groups_spec.rb spec/services/members/approve_access_request_service_spec.rb spec/features/security/project/snippet/private_access_spec.rb spec/features/projects/user_replaces_files_spec.rb spec/services/issues/build_service_spec.rb spec/requests/api/project_hooks_spec.rb spec/controllers/projects/project_members_controller_spec.rb spec/services/merge_requests/conflicts/resolve_service_spec.rb spec/migrations/migrate_stages_statuses_spec.rb spec/models/concerns/mentionable_spec.rb spec/controllers/projects/variables_controller_spec.rb spec/features/merge_request/user_sees_pipelines_spec.rb spec/controllers/sent_notifications_controller_spec.rb spec/lib/gitlab/project_authorizations_spec.rb spec/features/groups/members/leave_group_spec.rb spec/features/projects/files/edit_file_soft_wrap_spec.rb spec/features/admin/admin_labels_spec.rb spec/features/search/user_searches_for_wiki_pages_spec.rb spec/services/merge_requests/add_todo_when_build_fails_service_spec.rb spec/services/boards/issues/move_service_spec.rb spec/features/projects/settings/visibility_settings_spec.rb spec/finders/users_finder_spec.rb spec/features/merge_request/user_sees_mr_from_deleted_forked_project_spec.rb spec/lib/gitlab/background_migration/prepare_untracked_uploads_spec.rb spec/features/projects/members/group_members_spec.rb spec/workers/pipeline_metrics_worker_spec.rb spec/controllers/projects/clusters/user_controller_spec.rb spec/features/merge_request/user_sees_deleted_target_branch_spec.rb spec/lib/gitlab/database/rename_reserved_paths_migration/v1/rename_namespaces_spec.rb
  artifacts:
    expire_in: 31d
    when: always
    paths:
      - tmp/capybara/

##
# Trigger a package build in omnibus-gitlab repository
#
package-qa:
  <<: *dedicated-runner
  image: ruby:2.4-alpine
  before_script: []
  stage: build
  cache: {}
  when: manual
  script:
    - scripts/trigger-build-omnibus
  only:
    - //@gitlab-org/gitlab-ce
    - //@gitlab-org/gitlab-ee

setup-test-env:
  <<: *dedicated-runner
  <<: *except-docs
  <<: *use-pg
  stage: prepare
  cache:
    <<: *default-cache
  script:
    - bundle exec ruby -Ispec -e 'require "spec_helper" ; TestEnv.init'
    - scripts/gitaly-test-build # Do not use 'bundle exec' here
  artifacts:
    expire_in: 7d
    paths:
      - tmp/tests
      - config/secrets.yml

# Static analysis jobs
.ruby-static-analysis: &ruby-static-analysis
  variables:
    SIMPLECOV: "false"
    SETUP_DB: "false"

.rake-exec: &rake-exec
  <<: *dedicated-runner
  <<: *except-docs-and-qa
  <<: *pull-cache
  <<: *ruby-static-analysis
  stage: test
  script:
    - bundle exec rake $CI_JOB_NAME

static-analysis:
  <<: *dedicated-runner
  <<: *except-docs
  <<: *ruby-static-analysis
  stage: test
  script:
    - scripts/static-analysis
  cache:
    key: "ruby-2.3.6-with-yarn-and-rubocop"
    paths:
      - vendor/ruby
      - .yarn-cache/
      - tmp/rubocop_cache

downtime_check:
  <<: *rake-exec
  except:
    - master
    - tags
    - /^[\d-]+-stable(-ee)?$/
    - /(^docs[\/-].*|.*-docs$)/
    - /(^qa[\/-].*|.*-qa$)/

ee_compat_check:
  <<: *rake-exec
  except:
    - master
    - tags
    - /^[\d-]+-stable(-ee)?/
    - /^security-/
    - branches@gitlab-org/gitlab-ee
    - branches@gitlab/gitlab-ee
  retry: 0
  artifacts:
    name: "${CI_JOB_NAME}_${CI_COMIT_REF_NAME}_${CI_COMMIT_SHA}"
    when: always
    expire_in: 10d
    paths:
      - ee_compat_check/patches/*.patch

# DB migration, rollback, and seed jobs
.db-migrate-reset: &db-migrate-reset
  <<: *dedicated-runner
  <<: *except-docs-and-qa
  <<: *pull-cache
  stage: test
  script:
    - bundle exec rake db:migrate:reset

db:migrate:reset-pg:
  <<: *db-migrate-reset
  <<: *use-pg

db:migrate:reset-mysql:
  <<: *db-migrate-reset
  <<: *use-mysql

db:check-schema-pg:
  <<: *db-migrate-reset
  <<: *use-pg
  script:
    - source scripts/schema_changed.sh

.db-rollback: &db-rollback
  <<: *dedicated-runner
  <<: *except-docs-and-qa
  <<: *pull-cache
  stage: test
  script:
    - bundle exec rake db:rollback STEP=119
    - bundle exec rake db:migrate

db:rollback-pg:
  <<: *db-rollback
  <<: *use-pg

db:rollback-mysql:
  <<: *db-rollback
  <<: *use-mysql

.gitlab-setup: &gitlab-setup
  <<: *dedicated-runner
  <<: *except-docs-and-qa
  <<: *pull-cache
  stage: test
  variables:
    SIZE: "1"
    SETUP_DB: "false"
    CREATE_DB_USER: "true"
    FIXTURE_PATH: db/fixtures/development
  script:
    - git clone https://gitlab.com/gitlab-org/gitlab-test.git
       /home/git/repositories/gitlab-org/gitlab-test.git
    - scripts/gitaly-test-spawn
    - force=yes bundle exec rake gitlab:setup
  artifacts:
    when: on_failure
    expire_in: 1d
    paths:
      - log/development.log

gitlab:setup-pg:
  <<: *gitlab-setup
  <<: *use-pg

gitlab:setup-mysql:
  <<: *gitlab-setup
  <<: *use-mysql

sast:
  <<: *except-docs
  image: registry.gitlab.com/gitlab-org/gl-sast:latest
  variables:
    CONFIDENCE_LEVEL: 2
  before_script: []
  script:
    - /app/bin/run .
  artifacts:
    paths: [gl-sast-report.json]

qa:internal:
  <<: *dedicated-runner
  <<: *except-docs
  stage: test
  variables:
    SETUP_DB: "false"
  services: []
  script:
    - cd qa/
    - bundle install
    - bundle exec rspec

qa:selectors:
  <<: *dedicated-runner
  <<: *except-docs
  stage: test
  variables:
    SETUP_DB: "false"
  services: []
  script:
    - cd qa/
    - bundle install
    - bundle exec bin/qa Test::Sanity::Selectors

# Insurance in case a gem needed by one of our releases gets yanked from
# rubygems.org in the future.
cache gems:
  <<: *dedicated-runner
  <<: *pull-cache
  variables:
    SETUP_DB: "false"
  script:
    - bundle package --all --all-platforms
  artifacts:
    paths:
      - vendor/cache
  only:
    - master@gitlab-org/gitlab-ce
    - master@gitlab-org/gitlab-ee
    - tags

gitlab_git_test:
  <<: *dedicated-runner
  <<: *except-docs-and-qa
  variables:
    SETUP_DB: "false"
  before_script: []
  cache: {}
  script:
    - spec/support/prepare-gitlab-git-test-for-commit --check-for-changes
