image: "dev.gitlab.org:5005/gitlab/gitlab-build-images:ruby-2.3.3-golang-1.8-git-2.7-phantomjs-2.1-node-7.1-postgresql-9.6"

check_svg:
  script:
   - yarn install --pure-lockfile --cache-folder .yarn-cache
   - node scripts/check_svg.js
