- group: Cluster Health
  priority: 1
  metrics:
  - title: "CPU Usage"
    y_label: "CPU"
    required_metrics: ['container_cpu_usage_seconds_total']
    weight: 1
    queries:
    - query_range: 'sum(rate(container_cpu_usage_seconds_total{id="/"}[15m]))'
      label: Usage
      unit: "cores"
    - query_range: 'sum(kube_node_status_capacity_cpu_cores)'
      label: Capacity
      unit: "cores"
  - title: "Memory usage"
    y_label: "Memory"
    required_metrics: ['container_memory_usage_bytes']
    weight: 1
    queries:
    - query_range: 'sum(container_memory_usage_bytes{id="/"})/2^30'
      label: Usage
      unit: "GiB"
    - query_range: 'sum(kube_node_status_capacity_memory_bytes)/2^30'
      label: Capacity
      unit: "GiB"
