apiVersion: v1
kind: Pod
metadata:
  name:
  labels:
    environment:
spec:
  volumes:
  - name: repo
    emptyDir: {}
  containers:
  - name: fs
    image: micaelbergeron/gitlab-web-ide-fs
    ports:
    - containerPort: 9000
    volumeMounts:
      - name: repo
        mountPath: /export
    env:
      - name: REPO_URL
        value:
  - name: app
    image:
    ports:
      - containerPort:
    volumeMounts:
      - name: repo
        mountPath: /app
