# Here is a list of jobs that are scheduled to run periodically.
# We use a UNIX cron notation to specify execution schedule.
#
# Please read here for more information:
# https://github.com/ondrejbartas/sidekiq-cron#adding-cron-job

stuck_ci_builds_worker:
  cron: "0 0 * * *"
  class: "StuckCiBuildsWorker"
  queue: "default"

#
# GitLab EE only jobs:
#

historical_data_worker:
  cron: "0 12 * * *"
  class: "HistoricalDataWorker"
  queue: "default"

update_all_mirrors_worker:
  cron: "0 * * * *"
  class: "UpdateAllMirrorsWorker"
  queue: "default"

<% if Gitlab.config.ldap.enabled %>
# In addition to refreshing users when they log in,
# enabling this setting will refresh LDAP user membership once a day.
# Default time of the day when this will happen is at 1:30am server time.
ldap_sync_worker:
  cron: "30 1 * * *"
  class: "LdapSyncWorker"
  queue: "default"
<% end %>
